### ISSUE TITLE
Organisatorische context schrijven

### ISSUE THREAD

**Issue by hesteren** [hesteren/front-statuspagina-monta#3]
## Task
Organisatorische context schrijven om duidelijkheid te krijgen van het bedrijf waar ik stage loop

- [x] Beschrijving organisatie
- [x] Organogram
- [x] Processen waar de opdracht betrekking op heeft
- [x] Bedrijfs-/persoonsgegevens van alle betrokkenen
- [x] De positie/taken/verantwoordelijkheden van de student
- [x] De relatie van de stageopdracht met eventuele andere projecten
