### ISSUE TITLE
Theoretisch kader (onderzoek doen)

### ISSUE THREAD

**Issue by hesteren** [hesteren/front-statuspagina-monta#5]
## Task
Theoretisch kader (onderzoek doen) uitwerken zodat ik de belangrijkste begrippen die ik nodig heb afbaken

- [x] Definieer, bespreek en onderbouw vanuit de theorie de centrale begrippen en concepten uit de kwestie, 
context, opdracht, doelstelling en uit je hoofd- en deelvragen
- [x] Een beschrijving van de onderwerpen met bijbehorende literatuur die nog onderzocht moeten worden bij de 
uitwerking en beantwoording van je deelvragen
- [x] Een beschrijving en verantwoording van de gekozen methodische aanpak voor de beantwoording van de 
deelvragen
