### ISSUE TITLE
Kwaliteit

### ISSUE THREAD

**Issue by hesteren** [hesteren/front-statuspagina-monta#6]
## Task
Het kwaliteit hoofdstuk schrijven om kwaliteitscriteria vast te stellen waar het product uiteindelijk aan moet voldoen

- [x] Een beschrijving van op mede op de theorie gebaseerde kwaliteitscriteria waarop de resultaten zullen 
worden beoordeeld
- [x] Te gebruiken standaarden, methodieken en tools
- [x] Methodieken voor toetsen (documenten) en testen (eindresultaten)
